plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Jose Javier
description: Pseudorandom musings on programming, machine learning and puzzles
lang: en
locale: en_US
url: "https://blog.josejg.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
